# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_messenger}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Nelson"]
  s.date = %q{2010-02-02}
  s.description = %q{Standard facebook-style messaging system. Not bound to any friendship structure. Integrates directly into your User model. Allows for users to comment on a thread, leave a thread, and be updated when a thread is commented on.}
  s.email = %q{mdnelson30@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_messenger.gemspec",
     "generators/acts_as_messenger/acts_as_messenger_generator.rb",
     "generators/acts_as_messenger/templates/migrations/create_comments.rb",
     "generators/acts_as_messenger/templates/migrations/create_message_threads.rb",
     "generators/acts_as_messenger/templates/migrations/create_recipients.rb",
     "generators/acts_as_messenger/templates/models/comment.rb",
     "generators/acts_as_messenger/templates/models/message_thread.rb",
     "generators/acts_as_messenger/templates/models/recipient.rb",
     "lib/acts_as_messenger.rb",
     "lib/acts_as_messenger/thread.rb",
     "spec/acts_as_messenger_spec.rb",
     "spec/database.yml",
     "spec/debug.log",
     "spec/models/user.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mnelson/acts_as_messenger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Standard facebook-style messaging system. Not bound to any friendship structure. Integrates directly into your User model.}
  s.test_files = [
    "spec/acts_as_messenger_spec.rb",
     "spec/models/user.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<active_record>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<active_record>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<active_record>, [">= 0"])
  end
end

